--------------------------------------------------------
-- Archivo creado  - sábado-enero-14-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence HOTEL_ID
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."HOTEL_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence UNO
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."UNO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."CLIENTE" 
   (	"ID" NUMBER(*,0), 
	"CEDULA" VARCHAR2(10 BYTE), 
	"NOMBRES" VARCHAR2(50 BYTE), 
	"APELLIDOS" VARCHAR2(50 BYTE), 
	"TELEFONO" VARCHAR2(10 BYTE), 
	"DIRECCION" VARCHAR2(60 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECT" ;
--------------------------------------------------------
--  DDL for Table HOTEL
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."HOTEL" 
   (	"IDHOTEL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"UBICACION" VARCHAR2(40 BYTE), 
	"TELEFONO" VARCHAR2(10 BYTE), 
	"DISPONIBILIDAD" VARCHAR2(40 BYTE), 
	"SERVICIOS" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECT" ;
--------------------------------------------------------
--  DDL for Table VUELO
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."VUELO" 
   (	"IDVUELO" NUMBER(*,0), 
	"NOMBREAEROLINEA" VARCHAR2(40 BYTE), 
	"ORIGEN" VARCHAR2(40 BYTE), 
	"DESTINO" VARCHAR2(40 BYTE), 
	"ESCALA" VARCHAR2(40 BYTE), 
	"DISPONIBILIDAD" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECT" ;
REM INSERTING into PROYECTO.CLIENTE
SET DEFINE OFF;
Insert into PROYECTO.CLIENTE (ID,CEDULA,NOMBRES,APELLIDOS,TELEFONO,DIRECCION,EMAIL) values ('1','0954310736','MAX','C G','0962712966','JEFNW','KOSENMFKW');
Insert into PROYECTO.CLIENTE (ID,CEDULA,NOMBRES,APELLIDOS,TELEFONO,DIRECCION,EMAIL) values ('3','0955147871','ANGELA JAMILETH','VERA','0951564564','NEJIFNWJ','JNESFJWEN');
REM INSERTING into PROYECTO.HOTEL
SET DEFINE OFF;
Insert into PROYECTO.HOTEL (IDHOTEL,NOMBRE,UBICACION,TELEFONO,DISPONIBILIDAD,SERVICIOS) values ('7','TIERRITA','NORTE DE GUAYAQUIL','0948489498','NO','VARIOS');
REM INSERTING into PROYECTO.VUELO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Trigger TRIGUNO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "PROYECTO"."TRIGUNO" 
BEFORE INSERT ON cliente
FOR EACH ROW 
BEGIN 
SELECT uno.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "PROYECTO"."TRIGUNO" ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."CLIENTE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."CLIENTE" MODIFY ("CEDULA" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."CLIENTE" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."CLIENTE" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."CLIENTE" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."CLIENTE" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."CLIENTE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."CLIENTE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HOTEL
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."HOTEL" MODIFY ("IDHOTEL" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."HOTEL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."HOTEL" MODIFY ("UBICACION" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."HOTEL" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."HOTEL" MODIFY ("DISPONIBILIDAD" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."HOTEL" MODIFY ("SERVICIOS" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."HOTEL" ADD PRIMARY KEY ("IDHOTEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VUELO
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."VUELO" ADD PRIMARY KEY ("IDVUELO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECT"  ENABLE;
